cc = gcc
cflag = -Wall -g

main2_1:
	$(cc) $(cflag) main2_1.c -o main2_1
main2_2:
	$(cc) $(cflag) main2_2.c -o main2_2
main2_3:
	$(cc) $(cflag) main2_3.c -o main2_3
clean:
	rm -f *.o main2_1 main2_2 main2_3